services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_SECRET: ${APP_SECRET:-cR0oR5kN6gL2iL6uB2tF0eP7jB0wG8fJ}
      DATABASE_URL: "mysql://${MARIADB_USER:-iwasthere}:${MARIADB_PASSWORD:-iwasthere}@database:3306/${MARIADB_DATABASE:-iwasthere}?serverVersion=mariadb-11.4.10&charset=utf8mb4"
      MAILER_DSN: smtp://mailer:1025
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  database:
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-iwasthere}
      MARIADB_USER: ${MARIADB_USER:-iwasthere}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-iwasthere}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin:5
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
    volumes:
      - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
    depends_on:
      database:
        condition: service_healthy

  mailer:
    image: axllent/mailpit
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  database_data:
  vendor_data:
